"""creating bonuses

Revision ID: 21639c71aa87
Revises: 93d79a3728ac
Create Date: 2024-10-06 23:38:56.792242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21639c71aa87'
down_revision = '93d79a3728ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('amount_spending_required', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_id'), 'bonuses', ['id'], unique=False)
    op.alter_column('credit_cards', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('credit_cards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credit_cards', 'card_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('credit_cards', 'card_holder',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('credit_cards', 'welcome_bonus',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('credit_cards', 'welcome_spending_amount',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('credit_cards', 'welcome_spending_deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.alter_column('credit_cards', 'welcome_spending_deadline',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('credit_cards', 'welcome_spending_amount',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('credit_cards', 'welcome_bonus',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('credit_cards', 'card_holder',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('credit_cards', 'card_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('credit_cards', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credit_cards', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_bonuses_id'), table_name='bonuses')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
