"""Add password to users

Revision ID: 48a2c48da510
Revises: 4c9c3d6971c7
Create Date: 2024-10-07 23:02:12.891756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a2c48da510'
down_revision = '4c9c3d6971c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
