"""Fix id column in credit_cards

Revision ID: 9cc7aafccdd1
Revises: 0c3c33437459
Create Date: 2024-10-06 23:49:01.373462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc7aafccdd1'
down_revision = '0c3c33437459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
